# Type stubs for external libraries without official stubs
# This file provides basic type annotations for libraries used in the project

from typing import Any, Dict, List, Optional, Union

# joblib stubs
class Memory:
    def __init__(self, location: str, verbose: int = 0, mmap_mode: Optional[str] = None): ...
    def cache(self, func: Any, ignore: Optional[List[str]] = None, mmap_mode: Optional[str] = None) -> Any: ...
    def clear(self, warn: bool = True) -> None: ...

def dump(value: Any, filename: str, compress: Union[int, str, tuple] = 0, protocol: Optional[int] = None, cache_size: Optional[int] = None) -> List[str]: ...
def load(filename: str, mmap_mode: Optional[str] = None) -> Any: ...

# sklearn stubs (minimal)
from typing import Callable
import numpy as np

class BaseEstimator:
    def fit(self, X: np.ndarray, y: Optional[np.ndarray] = None) -> 'BaseEstimator': ...
    def predict(self, X: np.ndarray) -> np.ndarray: ...
    def predict_proba(self, X: np.ndarray) -> np.ndarray: ...

class ClassifierMixin:
    ...

class VotingClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, estimators: List[tuple], voting: str = 'hard', weights: Optional[List[float]] = None): ...
    def fit(self, X: np.ndarray, y: np.ndarray) -> 'VotingClassifier': ...
    def predict(self, X: np.ndarray) -> np.ndarray: ...
    def predict_proba(self, X: np.ndarray) -> np.ndarray: ...

class RandomForestClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, n_estimators: int = 100, max_depth: Optional[int] = None, random_state: Optional[int] = None): ...

class LogisticRegression(BaseEstimator, ClassifierMixin):
    def __init__(self, C: float = 1.0, random_state: Optional[int] = None): ...

# XGBoost stub
class XGBClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, n_estimators: int = 100, max_depth: int = 6, learning_rate: float = 0.1, random_state: Optional[int] = None): ...

# sklearn.preprocessing
class StandardScaler:
    def __init__(self): ...
    def fit(self, X: np.ndarray) -> 'StandardScaler': ...
    def transform(self, X: np.ndarray) -> np.ndarray: ...
    def fit_transform(self, X: np.ndarray) -> np.ndarray: ...

# sklearn.model_selection
class BaseCrossValidator:
    def split(self, X: np.ndarray, y: Optional[np.ndarray] = None, groups: Optional[np.ndarray] = None): ...

def train_test_split(*arrays: Any, test_size: Optional[float] = None, random_state: Optional[int] = None, stratify: Optional[np.ndarray] = None) -> tuple: ...

# sklearn.metrics
def accuracy_score(y_true: np.ndarray, y_pred: np.ndarray) -> float: ...
def precision_score(y_true: np.ndarray, y_pred: np.ndarray) -> float: ...
def recall_score(y_true: np.ndarray, y_pred: np.ndarray) -> float: ...
def f1_score(y_true: np.ndarray, y_pred: np.ndarray) -> float: ...

# plotly stubs (minimal)
class Figure:
    def show(self) -> None: ...
    def update_layout(self, **kwargs) -> None: ...

def express: Any
def graph_objects: Any
def subplots: Any