[global]
developmentMode = false

[server]
headless = false
port = 8501
enableCORS = true
enableXsrfProtection = false

[theme]
primaryColor = "#52A878"
backgroundColor = "#F3F1E7"
secondaryBackgroundColor = "#F3F1E7"
textColor = "#191919"
font = "serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false